model:
  variant: 'X1'
  input_size: 299
  covariate: null
  global_pool: 'avg'
  dropout: 0.5
  n_classes: 2
  ckpt: null

data:
  data_root_dir: '../data'
  meta_data_dir: '../labels/ucec_slide_labels_serous.csv'
  annotation_dir: null
  mask_id: 'basic'
  id_col: 'SlideID'
  label_col: 'Serous'
  covariate_col: null
  #  - 'Age'
  #  - 'BMI'
  new_split: true
  split_level: 'PatientID'
  ratio: 
    - 0.7
    - 0.1
    - 0.2
  mpp: 0.5
  res_factor: 
    - 1
    - 2
    - 4
  data_class: 'MultiResDicomDataset'
  slide_format: 'slide'

dataloader:
  batch_size: 32
  ddp_enabled: true
  num_gpu: 2
  num_workers: 8
  pin_memory: true
  prefetch_factor: 2

trainer:
  patience: 5
  max_epochs: 100
  batches_trn_epoch: 40000
  batches_val_epoch: 10000
  save_top_n: 2
  grad_batches: 1

optim:
  lr: 1e-4
  warmup_epochs: 5
  warmup_start_lr: 1e-5
  weight_decay: 0.01

run:
  name: 'test'
  debug: null
  exp_dir: '../results/241204'
  seed: 241204
  mode: 'train'
  saved_ckpt: null
  
  

  
